language: ruby
cache: bundler
rvm:
- 2.2
install: bundle install
script: bundle exec jekyll build
deploy:
  provider: pages
  github-token:
    secure: aowN/JhDRvVjudg9z7CeVDeA5PFaWBeknZM+Nj/e+TbzK3BfZhNyX1HLviLctTKKWuNtlPNpJQTHzAqdHNXjUPuUqrE9rCL4M16JDxgY9BoN0tm23rx3QXOm8wgEkkTSuEbL64005KQ3IUj1ppsLcx14cJ7nEepuZywlMzofXZ0NgSdkiu9k2zLuwipTao8carrh+xgKNrUtA2FKLXUWos07aGRe/tUKaMM/dalIPmpdEp1mVEF5OLw9Y8Re52DXpu+J2zX5lN9stMKPoM7nJUITJgdlyHyQ0GKOGojXHTu/e15YgsM33gTGsX8MdYqt8JLcOVW6v8J1dSTbp5GmVDEYFL7rdykSiJ8MqcmB1MG7Kn/qpBI6srWbWD8fx/xYc5TtlyhHBW7nCnaOQ2JGLjrrmkvadCXQgnolI6c1EkEUjsjoVUlqNmNXxInzTPcKB4+7DNEaVf0wy5EQ/+4xoKzGaAvoTZVHgGFJGKPclFTfxqqK8vClQqiD6XfAMgkGZ79QxnE5sdpr5/DuthkbNNFPyKzgcT8PMUq6OmquNFGsCk84jmNtykusYGJXiYfMeCqd0PsGKh1rQMV99JEZ/AD/NUIvwUpipNtCSP6OM3P3yKoV9Pd/iwXGFAj02MvICwbE9SN/qdtImeHqS1ZwDy4obtgbe8qts2UMqK0czOE=
  local-dir: _site
  skip_cleanup: true
